### ISSUE TITLE
Incompatibility with GoogleMutant plugin

### ISSUE THREAD

**Issue by robertharm** [torfsen/leaflet.zoomhome#7]
Hi Florian,

first thanks for providing this leaflet plugin - we are using it in our WordPress mapping plugin "Maps Marker Pro" (send me an email to get a free dev license ;-)

For the upcoming v3.0 release of our plugin, we also upgraded to GoogleMutant leaflet plugin for displaying Google maps. We now found that there seems to be an issue with leaflet.zoomhome and GoogleMutant: if the zoomhome button is clicked, tiles are missing: 

![zoom-home-issue](https://cloud.githubusercontent.com/assets/158669/23322828/0e32735a-fae6-11e6-8ac6-89f23bd7cf18.png)

We posted this as a new ticket at https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/issues/29 and also created a jsfiddle at https://jsfiddle.net/ennv4ckr/2/

As we havent found out why this issue occurs in the first place (especially as only setView() is called which shouldnt lead to an issue in our opinion), it would be great if you could have a short look at the issue too and tell us if you think this needs to be fixed by GoogleMutant only or if the issue could also be fixed within the leaflet.zoomhome repository.

Your reply would be much appreciated!
best,

Robert

**Comment by robertharm** [comment]
Sometimes summing up an issue leads to finding a fix :-) The issue was caused by the option `reset: true` which does not seem to be supported anymore in leaflet 1.0.3 and leads to missing tiles if GoogleMutant is used. Once this option (which we added due to reasons I cannot remember at the moment earlier) is removed, the issue is resolved. So sorry for bothering you with this...

**Comment by robertharm** [comment]
Actually my developers told me I was wrong and setting animate to false only circumvents the underlying problem caused by GoogleMutant - and the issue can even still occur when jumping far enough and animate = true gets ignored (e.g. 10 map widths). See https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/issues/29#note_24183504 for more details.

**Comment by torfsen** [comment]
@robertharm I don't think that this is an issue with *leaflet.zoomhome*, since it only uses Leaflet's [`Map.setView`](http://leafletjs.com/reference.html#map-setview) function. That is, this is either a problem in Leaflet itself or (more likely) in GoogleMutant.

I'm therefore closing this issue. Feel free to re-open in case you do think that it's an issue with *leaflet.zoomhome*.
